template_phrases:
  patterns:
    - regex: "ご.*ありがとうございます"
      min_frequency: 10
    - regex: "お.*いたします"
      min_frequency: 15
    - regex: ".*させていただ.*"
      min_frequency: 20
  ngram_range: [3, 7]
  pos_filter: ["名詞", "動詞", "助動詞"]

humble_phrases:
  patterns:
    - regex: "(まだまだ|不完全|未熟)"
      min_frequency: 5
    - regex: ".*ながら"
      min_frequency: 10
  ngram_range: [2, 5]
  
achievement_nouns:
  patterns:
    - pos_sequence: ["名詞-サ変接続", "動詞-自立"]
    - keywords: ["受賞", "達成", "成功", "獲得"]
  ngram_range: [1, 3]